### ISSUE TITLE
(#148-P5) Clerk - Supporter Contact info.  DUPE of 220

### ISSUE THREAD

**Issue by vmcf** [VMCAuctions/VMCAuction#215] opened 2019-02-19 16:29 UTC
(148)
Wireframe: clerk winning bidder	

Quicknotes:
Note: fields that are not mandatory for a supporter to "register and play" must be complete by the time they are paying for their won packages.

**Comment by rinebob** [comment] 2019-03-05 19:33
THIS IS A DUPLICATE OF #220 so is being archived

**Closed** 2019-03-05 19:34 UTC
